'use client';

import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-neutral-50 to-purple-50/30 dark:from-[#0f0b18] dark:to-[#1a1130] text-neutral-800 dark:text-neutral-200">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-10">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-purple-500 hover:text-purple-600 dark:hover:text-purple-400 transition-colors mb-6"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to App
          </Link>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-violet-600 bg-clip-text text-transparent">
            Terms of Service
          </h1>
          <p className="text-sm text-neutral-500 dark:text-neutral-400 mt-2">Last updated: April 1, 2026</p>
        </div>

        {/* Content */}
        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">1. Nature of Service</h2>
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/30 rounded-xl p-4 mb-4">
              <p className="font-medium text-red-800 dark:text-red-300 mb-2">⚠️ Important Disclaimer</p>
              <p className="text-red-700 dark:text-red-400">
                Friend AI is <strong>NOT</strong> a medical device, psychological therapy tool, or emergency service. 
                This platform does not provide professional counseling, medical diagnosis, or treatment advice.
              </p>
            </div>
            <p>Friend AI is an AI-powered chat companion application designed to provide:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Daily emotional companionship and friendly conversation</li>
              <li>Basic emotion tracking and self-reflection tools</li>
              <li>Knowledge Q&A and learning assistance</li>
              <li>Weather and schedule reminder services</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">2. AI Limitations</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>AI is not human.</strong> Responses are generated by large language models and may contain inaccurate, incomplete, or inappropriate content.</li>
              <li><strong>Not a substitute for professionals.</strong> Information provided by the AI should never replace advice from doctors, therapists, lawyers, or other qualified professionals.</li>
              <li><strong>Emotion analysis limitations.</strong> AI emotion detection is text-based and cannot fully or accurately assess a user&apos;s true psychological state.</li>
              <li><strong>Crisis detection limitations.</strong> While our system includes crisis detection, it cannot guarantee detection of all crisis situations. In emergencies, always contact local emergency services first.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">3. Crisis Intervention Disclaimer</h2>
            <p>Our platform includes automated safety detection that:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Makes best-effort attempts to identify self-harm/suicide intent and extreme speech</li>
              <li>Automatically activates Safe Mode and provides crisis hotline information when high-risk content is detected</li>
              <li>Notifies platform administrators for manual review in extreme cases</li>
            </ul>
            <p className="mt-3 font-medium">
              However, we explicitly disclaim liability for:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-1">
              <li>Undetected crisis situations (false negatives)</li>
              <li>Delayed system responses</li>
              <li>Any consequences arising from missed or delayed detection</li>
            </ul>
            <p className="mt-3">
              In genuine emergencies, users should always contact <strong>local emergency services</strong> and 
              <strong> professional crisis hotlines</strong> directly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">4. User Responsibilities</h2>
            <p>By using this platform, you agree to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Provide truthful information (especially age)</li>
              <li>Use the platform lawfully — no illegal activities</li>
              <li>Not attempt to jailbreak, manipulate, or bypass AI safety filters</li>
              <li>Not post terrorism, hate speech, violent threats, or other prohibited content</li>
              <li>Understand AI limitations and not rely on AI advice for professional decisions</li>
              <li>Contact professional services in genuine emergencies, not rely on this platform</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">5. Account Restrictions</h2>
            <p>To protect platform safety, the following restriction tiers apply for extreme speech violations:</p>
            <div className="overflow-x-auto mt-2">
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="border-b border-neutral-200 dark:border-neutral-700">
                    <th className="text-left py-2 pr-4 font-medium">Violation</th>
                    <th className="text-left py-2 font-medium">Consequence</th>
                  </tr>
                </thead>
                <tbody className="text-neutral-600 dark:text-neutral-400">
                  <tr className="border-b border-neutral-100 dark:border-neutral-800">
                    <td className="py-2 pr-4">1st offense</td>
                    <td className="py-2">Warning recorded</td>
                  </tr>
                  <tr className="border-b border-neutral-100 dark:border-neutral-800">
                    <td className="py-2 pr-4">2nd offense</td>
                    <td className="py-2">24-hour temporary restriction</td>
                  </tr>
                  <tr className="border-b border-neutral-100 dark:border-neutral-800">
                    <td className="py-2 pr-4">3rd offense</td>
                    <td className="py-2">7-day temporary restriction</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">4th+ offense</td>
                    <td className="py-2">Permanent restriction</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">6. Disclaimers</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>The service is provided &quot;as-is&quot; and &quot;as-available&quot; without warranties of any kind</li>
              <li>We do not guarantee uninterrupted service availability</li>
              <li>We do not guarantee the accuracy of AI-generated content</li>
              <li>We are not responsible for third-party service interruptions or policy changes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, the Platform and its operators shall not be liable for 
              any direct, indirect, incidental, special, punitive, or consequential damages arising from the 
              use or inability to use this service. This includes but is not limited to: data loss, personal 
              injury, emotional distress, or any other damages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">8. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of <strong>Malaysia</strong>. 
              Any disputes arising shall be resolved through friendly negotiation first. If negotiation fails, 
              disputes shall be submitted to the courts of competent jurisdiction in Malaysia.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated 
              via in-app notification and email. Continued use of the Platform constitutes acceptance of 
              the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 mb-3">10. Contact</h2>
            <p>
              For questions about these Terms, contact us at: <strong>liangszekai@gmail.com</strong>
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-neutral-200 dark:border-neutral-800 flex justify-between items-center text-xs text-neutral-400">
          <span>© 2026 Friend AI. All rights reserved.</span>
          <Link href="/privacy" className="text-purple-500 hover:text-purple-600 transition-colors">
            ← Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
}
